name: CI

on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Git - Checkout
      uses: actions/checkout@v1
    - name: Git - Prepare for a push
      run: |
        git config --global user.email "tech@tipser.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git checkout "${GITHUB_REF#refs/heads/}"
    - name: Build - Print NodeJS version
      run: node --version
    - name: Project - Install dependencies
      run: npm ci
    - name: Project - Build and deploy
      run: npm run deploy
